# permissions for end users to edit derivedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: derivedsecret-editor-role
rules:
- apiGroups:
  - secrets.meln5674.github.com
  resources:
  - derivedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.meln5674.github.com
  resources:
  - derivedsecrets/status
  verbs:
  - get
