# permissions for end users to view derivedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: derivedsecret-viewer-role
rules:
- apiGroups:
  - secrets.meln5674.github.com
  resources:
  - derivedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.meln5674.github.com
  resources:
  - derivedsecrets/status
  verbs:
  - get
