//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Andrew Melnick

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinaryTarget) DeepCopyInto(out *BinaryTarget) {
	*out = *in
	in.TargetBase.DeepCopyInto(&out.TargetBase)
	if in.Literal != nil {
		in, out := &in.Literal, &out.Literal
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinaryTarget.
func (in *BinaryTarget) DeepCopy() *BinaryTarget {
	if in == nil {
		return nil
	}
	out := new(BinaryTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DerivedSecret) DeepCopyInto(out *DerivedSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DerivedSecret.
func (in *DerivedSecret) DeepCopy() *DerivedSecret {
	if in == nil {
		return nil
	}
	out := new(DerivedSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DerivedSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DerivedSecretList) DeepCopyInto(out *DerivedSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DerivedSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DerivedSecretList.
func (in *DerivedSecretList) DeepCopy() *DerivedSecretList {
	if in == nil {
		return nil
	}
	out := new(DerivedSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DerivedSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DerivedSecretSpec) DeepCopyInto(out *DerivedSecretSpec) {
	*out = *in
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]SensitiveReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]BinaryTarget, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.StringData != nil {
		in, out := &in.StringData, &out.StringData
		*out = make(map[string]StringTarget, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Prefab != nil {
		in, out := &in.Prefab, &out.Prefab
		*out = new(Prefabs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DerivedSecretSpec.
func (in *DerivedSecretSpec) DeepCopy() *DerivedSecretSpec {
	if in == nil {
		return nil
	}
	out := new(DerivedSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DerivedSecretStatus) DeepCopyInto(out *DerivedSecretStatus) {
	*out = *in
	if in.LastSync != nil {
		in, out := &in.LastSync, &out.LastSync
		*out = (*in).DeepCopy()
	}
	if in.LastSyncAttempt != nil {
		in, out := &in.LastSyncAttempt, &out.LastSyncAttempt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DerivedSecretStatus.
func (in *DerivedSecretStatus) DeepCopy() *DerivedSecretStatus {
	if in == nil {
		return nil
	}
	out := new(DerivedSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prefabs) DeepCopyInto(out *Prefabs) {
	*out = *in
	if in.CopyAll != nil {
		in, out := &in.CopyAll, &out.CopyAll
		*out = new(bool)
		**out = **in
	}
	if in.CopyIncluding != nil {
		in, out := &in.CopyIncluding, &out.CopyIncluding
		*out = make([]ReferenceSubset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CopyExcluding != nil {
		in, out := &in.CopyExcluding, &out.CopyExcluding
		*out = make([]ReferenceSubset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prefabs.
func (in *Prefabs) DeepCopy() *Prefabs {
	if in == nil {
		return nil
	}
	out := new(Prefabs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reference) DeepCopyInto(out *Reference) {
	*out = *in
	in.ConfigMapRef.DeepCopyInto(&out.ConfigMapRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reference.
func (in *Reference) DeepCopy() *Reference {
	if in == nil {
		return nil
	}
	out := new(Reference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferenceSubset) DeepCopyInto(out *ReferenceSubset) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllKeys != nil {
		in, out := &in.AllKeys, &out.AllKeys
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferenceSubset.
func (in *ReferenceSubset) DeepCopy() *ReferenceSubset {
	if in == nil {
		return nil
	}
	out := new(ReferenceSubset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SensitiveReference) DeepCopyInto(out *SensitiveReference) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.ConfigMapEnvSource)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretEnvSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SensitiveReference.
func (in *SensitiveReference) DeepCopy() *SensitiveReference {
	if in == nil {
		return nil
	}
	out := new(SensitiveReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringTarget) DeepCopyInto(out *StringTarget) {
	*out = *in
	in.TargetBase.DeepCopyInto(&out.TargetBase)
	if in.Literal != nil {
		in, out := &in.Literal, &out.Literal
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringTarget.
func (in *StringTarget) DeepCopy() *StringTarget {
	if in == nil {
		return nil
	}
	out := new(StringTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetBase) DeepCopyInto(out *TargetBase) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
	if in.Overwrite != nil {
		in, out := &in.Overwrite, &out.Overwrite
		*out = new(bool)
		**out = **in
	}
	if in.IsMap != nil {
		in, out := &in.IsMap, &out.IsMap
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetBase.
func (in *TargetBase) DeepCopy() *TargetBase {
	if in == nil {
		return nil
	}
	out := new(TargetBase)
	in.DeepCopyInto(out)
	return out
}
